In [2]:
%load_ext autoreload
%autoreload 2

In [8]:
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
from scipy import linalg

In [9]:
A = np.array([[1,3,5],[2,5,1],[2,3,8]])
A

array([[1, 3, 5],
       [2, 5, 1],
       [2, 3, 8]])

In [11]:
linalg.inv(A)

array([[-1.48,  0.36,  0.88],
       [ 0.56,  0.08, -0.36],
       [ 0.16, -0.12,  0.04]])

In [13]:
np.allclose(np.eye(3), A.dot(linalg.inv(A)))

True

In [64]:
def translate(*args ):
    l=len(args)
    M=np.eye(l+1)
    for i, arg in enumerate(args):
        M[i,l]=arg
    return(M)

In [76]:
translate(1)

array([[1., 1.],
       [0., 1.]])

In [77]:
translate(1,2)

array([[1., 0., 1.],
       [0., 1., 2.],
       [0., 0., 1.]])

In [78]:
translate(1,2,3)

array([[1., 0., 0., 1.],
       [0., 1., 0., 2.],
       [0., 0., 1., 3.],
       [0., 0., 0., 1.]])

In [68]:
A=np.array([[1], [1]])
A

array([[1],
       [1]])

In [80]:
M=translate(1)
M

array([[1., 1.],
       [0., 1.]])

In [81]:
np.dot(M, A)

array([[2.],
       [1.]])

In [82]:
M=translate(1, scale=2)
M

array([[1., 1.],
       [0., 2.]])

In [90]:
def origin(n=3):
    A=np.zeros((n+1,1))
    A[n,0]=1
    return A
origin()

array([[0.],
       [0.],
       [0.],
       [1.]])

In [95]:
translate(*[0]*3)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [96]:
np.dot(translate(0,0,0), origin())

array([[0.],
       [0.],
       [0.],
       [1.]])

A translation is an affine transformation with no fixed points. Matrix multiplications always have the origin as a fixed point. Nevertheless, there is a common workaround using homogeneous coordinates to represent a translation of a vector space with matrix multiplication: Write the 3-dimensional vector w = (wx, wy, wz) using 4 homogeneous coordinates as w = (wx, wy, wz, 1).

To translate an object by a vector v, each homogeneous vector p (written in homogeneous coordinates) can be multiplied by this translation matrix:

$$
T_{\mathbf{v}} = 
\begin{bmatrix}
1 & 0 & 0 & v_x \\
0 & 1 & 0 & v_y \\
0 & 0 & 1 & v_z \\
0 & 0 & 0 & 1
\end{bmatrix}
$$

As shown below, the multiplication will give the expected result:

$$
{\displaystyle T_{\mathbf {v} }\mathbf {p} ={\begin{bmatrix}1&0&0&v_{x}\\0&1&0&v_{y}\\0&0&1&v_{z}\\0&0&0&1\end{bmatrix}}{\begin{bmatrix}p_{x}\\p_{y}\\p_{z}\\1\end{bmatrix}}={\begin{bmatrix}p_{x}+v_{x}\\p_{y}+v_{y}\\p_{z}+v_{z}\\1\end{bmatrix}}=\mathbf {p} +\mathbf {v} }  T_{\mathbf{v}} \mathbf{p} =
\begin{bmatrix}
1 & 0 & 0 & v_x \\
0 & 1 & 0 & v_y\\
0 & 0 & 1 & v_z\\
0 & 0 & 0 & 1
\end{bmatrix}
\begin{bmatrix}
p_x \\ p_y \\ p_z \\ 1
\end{bmatrix}
=
\begin{bmatrix}
p_x + v_x \\ p_y + v_y \\ p_z + v_z \\ 1
\end{bmatrix}
= \mathbf{p} + \mathbf{v} 
$$

The inverse of a translation matrix can be obtained by reversing the direction of the vector:

$$
T^{-1}_{\mathbf{v}} = T_{-\mathbf{v}}
$$

Similarly, the product of translation matrices is given by adding the vectors:

$$
T_{\mathbf{u}}T_{\mathbf{v}} = T_{\mathbf{u}+\mathbf{v}}
$$

Because addition of vectors is commutative, multiplication of translation matrices is therefore also commutative (unlike multiplication of arbitrary matrices).

In [104]:
T=np.eye(4)
T[0,3]=2
T[1,3]=3
T[2,3]=4
T

array([[1., 0., 0., 2.],
       [0., 1., 0., 3.],
       [0., 0., 1., 4.],
       [0., 0., 0., 1.]])

In [105]:
T=np.eye(4)
T[0,3]=2
T[1,3]=3
T[2,3]=4
T

array([[1., 0., 0., 2.],
       [0., 1., 0., 3.],
       [0., 0., 1., 4.],
       [0., 0., 0., 1.]])

In [106]:
def translate(x=0, y=0, z=0):
    """3D translate"""
    T=np.eye(4)
    T[0,3]=x
    T[1,3]=y
    T[2,3]=z
    return T
translate()

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [107]:
translate(0,1,0)

array([[1., 0., 0., 0.],
       [0., 1., 0., 1.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [109]:
args=[0, 1, 0]
np.array(args).squeeze()

array([0, 1, 0])

In [124]:
def translate(*args):
    """generic translate transform generator."""
    T=np.eye(len(args)+1)
    T[0:-1,-1]=np.array(args).squeeze()
    return T
translate(2)

array([[1., 2.],
       [0., 1.]])

In [125]:
translate(0,2)

array([[1., 0., 0.],
       [0., 1., 2.],
       [0., 0., 1.]])

In [126]:
translate(0,0,2)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 2.],
       [0., 0., 0., 1.]])

> In mathematics, the dot product or scalar product is an algebraic operation that takes two equal-length sequences of numbers (usually coordinate vectors) and returns a single number. In Euclidean geometry, the dot product of the Cartesian coordinates of two vectors is widely used and often called inner product (or rarely projection product); see also inner product space.

Algebraic definition
The dot product of two vectors a = [a1, a2, …, an] and b = [b1, b2, …, bn] is defined as:[1]

$$
{\displaystyle \mathbf {\color {red}a} \cdot \mathbf {\color {blue}b} =\sum _{i=1}^{n}{\color {red}a}_{i}{\color {blue}b}_{i}={\color {red}a}_{1}{\color {blue}b}_{1}+{\color {red}a}_{2}{\color {blue}b}_{2}+\cdots +{\color {red}a}_{n}{\color {blue}b}_{n}}$$
